### ISSUE TITLE
Review addition of libjpeg-turbo and libjpeg-turbo-devel

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/s2i-python#109]
This is a follow up on https://github.com/openshift/sti-python/pull/102. Moving the discussion here for it's easier to track an open issue than a merged PR (rather easy to forget).

Open questions:

- [ ] Check where the libs belong, it anywhere in the official images.
  It's unclear what apps or Python libraries depend on those libs. Perhaps it doesn't belong in the Python layer, but in sti-base? Or in a specialized derivative of sti-python?
  Quoting @bparees:
  > @donnydavis can you elaborate on why you consider this to be a common dependency?

- [ ] The patch was applied only to the 2.7 image (update 3.3 and 3.4 in a follow up?)
- [ ] The increase in image size is of ~3 MB. Do we consider that OK?

```console
$ docker images | grep jpeg
python-27-jpeg                                      latest              15639fcae25f        29 seconds ago      657.7 MB
python-27-no-jpeg                                   latest              804931d10c74        2 days ago          654.8 MB
```

Something else to consider?

**Comment by bparees** [comment]
i'm ok with the 3mb size increase, assuming we can satisfy the other questions.

and yes, definitely should be done in 3.3 and 3.4 as well (assuming we keep it).  If we can't justify it in those, then it probably doesn't belong in 2.7 either (unless it's been supplanted by a different library used by python3.3/3.4 apps).

**Comment by rhcarvalho** [comment]
We don't know yet the original use case, but I was extrapolating that for whatever uses some libjpeg in Python, there'd be a similar "need" in Perl, Ruby, PHP, etc...

Looking at the existing yum packages we install at the sti-python level, those are only Python related (like pip), and httpd is the only exception to that so far.

**Comment by bparees** [comment]
@donnydavis can you weigh in here on what your use cases were?  we're having trouble justifying keeping the jpeg libs in the common image w/o your help.

**Comment by bparees** [comment]
at this point i'm inclined to just close this.  we'll leave the library in python2.7 but not add it to the other versions.  if a request comes to add it to 3.3 or 3.4 we can revisit this discussion about where it belongs, whether it belongs, etc.

any objections @rhcarvalho ?

**Comment by rhcarvalho** [comment]
@bparees it will stand out when diff'ing the multiple image versions, but I'm okay with whatever decision you make.

**Comment by bparees** [comment]
yeah, minor annoyance, i think we can live with it.

**Comment by donnydavis** [comment]
This should be closed, pillow will now build. Sorry for the delays in getting back to you

**Comment by rhcarvalho** [comment]
> This should be closed, pillow will now build. Sorry for the delays in getting back to you

Do you mean that the libs are not needed?
