### ISSUE TITLE
Log when use APP_FILE

### ISSUE THREAD

**Issue by geovanaSouza** [openshift/s2i-python#115]
Hello,

I have an application that is started with environment variable APP_FILE. When i execute the app in my local environment show the message in console:
[*] Waiting Messages. Press CTRL+C to finish

But, when I execute in the Openshift, the message doesn't appear. If I access the app in Openshift with "oc rsh" and manually execute /usr/libexec/s2i/run appears the message.

In my app, the message log is generated by the code bellow:
print('[*] Waiting Messages. Press CTRL+C to finish')

Can you help me?

**Comment by mnagy** [comment]
I'm not 100% sure I understand your problem. Could you please provide a simple reproducer script and steps to reproduce? Also, which version of Python?

**Comment by geovanaSouza** [comment]
We did more tests and isolate the problem. When we isolate the code, the problem doesn't happen.
My developer team will investigate the code now.

Apologies for the inconvenience.

**Comment by geovanaSouza** [comment]
Resolved set environment variable:

PYTHONUNBUFFERED=true

**Comment by mnagy** [comment]
Hi, could you please elaborate? Is this something that could happen to
ither people? Is it something preventable by us? What does the mentioned
environment variable do?

**Comment by geovanaSouza** [comment]
Set PYTHONUNBUFFERED works for me, but i don't know if this is good practice. In the python manual page don't show many information about this parameter:
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED


Steps to reproduce:
oc new-app python:3.4 --name=test-log https://github.com/geovanaSouza/python_runner.git -e APP_FILE=python_runner2.py -l app=test-log

In the log don't show any message. When I wait for sometime (about 20 minutes) show the message in the log.

But, when I set PYTHONUNBUFFERED:
oc env dc test-log PYTHONUNBUFFERED=true

Show the message instantly for my app:
---> Running application from Python script (python_runner2.py) ...
App begin
Message loop
Message loop
Message loop
Message loop
Message loop
Message loop

**Comment by geovanaSouza** [comment]
I think when I set this parameter the message is stored in memory buffer. When the buffer is full, the message's show in the log.
