### ISSUE TITLE
Please add Python 3.5

### ISSUE THREAD

**Issue by Fale** [openshift/s2i-python#75]
Python 3.5 [has been released](https://www.python.org/downloads/release/python-350/) and it wuold be nice to have it available :)

**Comment by mfojtik** [comment]
@hhorak @sYnfo FYI

**Comment by bparees** [comment]
@hhorak is python 3.5 on the SCL roadmap?

**Comment by hhorak** [comment]
Yeah, we're about to start working on it these days..

**Comment by Grief** [comment]
+1 for 3.5 support.
BTW there is already a repo which provides a cartridge with 3.5: https://github.com/Praisebetoscience/openshift-cartridge-python-3.5

**Comment by bparees** [comment]
@Grief cartridges are an openshift v2 concept, this repo is for openshift v3 which uses docker images, not cartridges.

**Comment by Grief** [comment]
@bparees I just put this link for the interest of those who want python3.5 now. By the way, don't you know the date when 3.5 will be added officially?

**Comment by bparees** [comment]
@Grief I don't believe it has been announced officially, no.

**Comment by YAmikep** [comment]
If I well understand, this is not for Openshift Online?
Openshift online is still on Openshift v2 with cartridges, correct?

Any idea if Openshift Online will move to Openshift v3 so that it will support python 3.5 via this docker image?

The python 3.5 cartridge (https://github.com/Praisebetoscience/openshift-cartridge-python-3.5) does not work on Openshift Online.

Thanks

**Comment by bparees** [comment]
Yes online will be moving to v3, keep an eye out for announcements.

**Comment by YAmikep** [comment]
@bparees Do you know whether it is weeks/months/years or nothing is planned for now? Thanks

**Comment by bparees** [comment]
probably weeks or months.

**Comment by treefroog** [comment]
@bparees any updates on Python 3.5? @

**Comment by bparees** [comment]
@hhorak would be the one to speak to dates for python3.5.

**Comment by psddp** [comment]
Upvote for python 3.5

**Comment by Grief** [comment]
Hello there! How can python3.5 cartridge be installed now? Cannot find it in the cartridge list

**Comment by bparees** [comment]
@Grief are you using openshift v2 or v3?  this new image is for v3, it will be available soon but not quite yet.  there are no plans to introduce a v3.5 cartridge for openshift v2.

**Comment by Grief** [comment]
@bparees I mentioned https://www.openshift.com/ - is it v2 or v3?

**Comment by bparees** [comment]
@Grief that environment is v2, we are beginning to roll out the availability of our v3 online environment but it's not open to the public yet.

**Comment by Grief** [comment]
Got it. Can I kindly ask for the estimations? Will it happen until the end of the year?

**Comment by bparees** [comment]
estimations of v3 online availability?  @sspeiche is better equipped to answer that.

**Comment by sspeiche** [comment]
@Grief we have no announced dates for v3 online to share at this moment. We have plans and we will be sharing those plans when appropriate, keep an eye out at https://openshift.com for announcements.

somethings around "it" will happen by the end of the year, sorry to be so vague but this is where we are

**Comment by lhonda** [comment]
:+1:

**Comment by javawolfpack** [comment]
That is kind of vague... Thankfully got a DIY cartridge w/ Python 3.5 & Django 1.9 starter repo functioning yesterday after a week of work. So I'm able to get by while we wait... @Grief your fork of Praisebetoscience's cartridge was very helpful.
